trigger:
- main

schedules:
- cron: "24 16 * * 3"
  displayName: Weekly CodeQL Scan
  branches:
    include:
    - main
  always: true

pool:
  name: Default   # self-hosted agent

steps:
- checkout: self

- task: CodeQLInitialize@0
  inputs:
    languages: java

- task: CodeQLAutobuild@0

- task: CodeQLAnalyze@0
